### PR TITLE
Charger controller software shutdown revision

### PR DESCRIPTION
**Pull request by joshkirsh720**
# Pull Request (PR) into Code-2020

***Your PR should not cause any merge conflicts, so please merge the `master` branch into your branch before submitting. It is your responsibility to ensure that the merge does not break something before submitting. [Here](https://guides.github.com/features/mastering-markdown/) is a good resource for markdown formatting as you fill out this template. See this [example](). Feel free to ask any electrical lead if you have any questions! Delete this block when actually making your PR!***

## Code Description
Charger Controller code was changed in Vehicle/Charger_Control_Unit/Charger_Control_Unit.ino

Check was added to set software shutdown low if either shutdown_b or shutdown_c ever read low. The goal of this is to ensure that charging can never resume after a fault has been detected. This previously could have happened if shutdown_b or c ever went low and then returned high.

## Testing Description
Code was tested by connecting the teensy 3.2 to my computer and reading from the serial monitor while powering the board and tying bms_ok and okhs to high. I would then latch the relays and restart the teensy, this would engage all three relays. I would then disconnect either bms_ok and okhs from high and observe software_shutdown also going low, as intended in the code. I also monitored the state of each signal according to the teensy through the serial monitor and everything was as expected.

## Checklist
- [ ] Is this code linked to a new board or board rev?
- - [ ] Is *there a PR* for that board in `circuits-2020`? If so, please pause until that PR is merged.
- [X] Did you test the code in real-world conditions before submitting?
- - [X] Did you *use CPU Speed = 76 Mhz and Optimize = Faster* when testing?
- [X] Did you pull `master` into your branch?
- - [X] Did you *check for merge conflicts*?
- - [X] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
- [X] Did you fill out the above template?
- [X] Did you assign the right people for review (on the right)?

### CODE REVIEW

**Comment by 19etweinstock** [comment]
What about code for the watchdog?

**Comment by joshkirsh720** [comment]
Not including that code because the revision with the watchdog isn't done yet.

**Comment by Arvind-Srinivasan** [comment]
Test comment

**Review by atulmerchia — CHANGES_REQUESTED** [review]

**Review by shaand1 — APPROVED** [review]

**Review by shaand1 — APPROVED** [review]

**Review by 19etweinstock — APPROVED** [review]
asdfghjkl

**Pull request merged**
